home: [[0.0,0.0]]

front: [[0.0, 0.0]]
front_up: [[1.0, -0.5]]
front_up_full: [[3.14, -1.57]]
front_down: [[-1.0, 0.5]]
front_down_full: [[-3.14, 1.57]]

back: [[0.0, 3.14]]
back_left: [[0.0, 3.14]]
back_right: [[0.0, -3.14]]
back_up: [[-1.0, 3.64]]
back_up_full: [[-3.14, 4.71]]
back_down: [[1.0, 2.34]]
back_down_full: [[3.14, 1.57]]

left: [[0.0, 1.57]]
right: [[0.0, -1.57]]

nod: [[-1.0, 0.5], [0.0,0.0]]
shake: [[0.0, 1.57], [0.0, -1.57], [0.0, 1.57], [0.0,0.0]]
