torso_cam3d_right_rgb_camera_info: {  
  hz: 55.25,
  hzerror: 54.75,
  topic: /torso_cam3d_right/rgb/camera_info,
  test_duration: 2.0,
  wait_time: 30.0
}
torso_cam3d_right_depth_camera_info: {  
  hz: 55.25,
  hzerror: 54.75,
  topic: /torso_cam3d_right/depth/camera_info,
  test_duration: 2.0,
  wait_time: 30.0
}
torso_cam3d_right_depth_image_raw: {  
  hz: 55.25,
  hzerror: 54.75,
  topic: /torso_cam3d_right/depth/image_raw,
  test_duration: 2.0,
  wait_time: 30.0
}
torso_cam3d_right_depth_image: {  
  hz: 55.25,
  hzerror: 54.75,
  topic: /torso_cam3d_right/depth/image,
  test_duration: 2.0,
  wait_time: 30.0
}
torso_cam3d_right_depth_points: {  
  hz: 55.25,
  hzerror: 54.75,
  topic: /torso_cam3d_right/depth/points,
  test_duration: 2.0,
  wait_time: 30.0
}
torso_cam3d_right_rgb_image_color: {  
  hz: 55.25,
  hzerror: 54.75,
  topic: /torso_cam3d_right/rgb/image_color,
  test_duration: 2.0,
  wait_time: 30.0
}
torso_cam3d_right_rgb_image_raw: {  
  hz: 55.25,
  hzerror: 54.75,
  topic: /torso_cam3d_right/rgb/image_raw,
  test_duration: 2.0,
  wait_time: 30.0
}
