prosilica_left_camera_info: {  
  hz: 55.25,
  hzerror: 54.75,
  topic: /stereo/left/camera_info,
  test_duration: 2.0,
  wait_time: 30.0
}
prosilica_left_image_raw: {  
  hz: 55.25,
  hzerror: 54.75,
  topic: /stereo/left/image_raw,
  test_duration: 2.0,
  wait_time: 30.0
}

